name: aiPixels
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip 22.2.2
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
    - pip:
        - absl-py==1.3.0
        - accelerate==0.14.0
        - addict==2.4.0
        - aiohttp==3.8.3
        - aiosignal==1.3.1
        - albumentations==0.4.3
        - antlr4-python3-runtime==4.8
        - async-timeout==4.0.2
        - attrs==22.1.0
        - basicsr==1.4.2
        - cachetools==5.2.0
        - chardet==4.0.0
        - clean-fid==0.1.34
        - click==8.1.3
        - clip-anytorch==2.5.0
        - colorama==0.4.6
        - contourpy==1.0.6
        - cycler==0.11.0
        - docker-pycreds==0.4.0
        - einops==0.3.0
        - facexlib==0.2.5
        - filelock==3.8.0
        - filterpy==1.4.5
        - font-roboto==0.0.1
        - fonts==0.0.3
        - fonttools==4.38.0
        - frozenlist==1.3.3
        - fsspec==2022.11.0
        - ftfy==6.1.1
        - future==0.18.2
        - gitdb==4.0.9
        - gitpython==3.1.29
        - google-auth==2.14.1
        - google-auth-oauthlib==0.4.6
        - grpcio==1.51.0
        - huggingface-hub==0.11.0
        - idna==2.10
        - imageio==2.9.0
        - imageio-ffmpeg==0.4.2
        - imgaug==0.2.6
        - importlib-metadata==5.0.0
        - joblib==1.2.0
        - jsonmerge==1.9.0
        - jsonschema==4.17.0
        - k-diffusion==0.0.10
        - kiwisolver==1.4.4
        - kornia==0.6.0
        - lark==1.1.4
        - llvmlite==0.39.1
        - lmdb==1.3.0
        - markdown==3.4.1
        - markupsafe==2.1.1
        - matplotlib==3.6.2
        - multidict==6.0.2
        - mypy-extensions==0.4.3
        - networkx==2.8.8
        - numba==0.56.4
        - numexpr==2.8.4
        - oauthlib==3.2.2
        - omegaconf==2.1.1
        - opencv-python==4.5.5.64
        - opencv-python-headless==4.6.0.66
        - packaging==21.3
        - pandas==1.5.1
        - pathtools==0.1.2
        - piexif==1.1.3
        - promise==2.3
        - protobuf==3.20.3
        - psutil==5.9.4
        - pudb==2019.2
        - pyasn1==0.4.8
        - pyasn1-modules==0.2.8
        - pydeprecate==0.3.1
        - pygments==2.13.0
        - pyparsing==3.0.9
        - pyre-extensions==0.0.23
        - pyrsistent==0.19.2
        - pyside6==6.4.0.1
        - pyside6-addons==6.4.0.1
        - pyside6-essentials==6.4.0.1
        - python-dateutil==2.8.2
        - pytorch-lightning==1.4.2
        - pytz==2022.6
        - pywavelets==1.4.1
        - pyyaml==6.0
        - regex==2022.10.31
        - requests==2.25.1
        - requests-oauthlib==1.3.1
        - resize-right==0.0.2
        - rsa==4.9
        - scikit-image==0.19.3
        - scikit-learn==1.1.3
        - scipy==1.9.3
        - sentry-sdk==1.11.0
        - setproctitle==1.3.2
        - shiboken6==6.4.0.1
        - shortuuid==1.0.11
        - smmap==5.0.0
        - tb-nightly==2.12.0a20221121
        - tensorboard==2.11.0
        - tensorboard-data-server==0.6.1
        - tensorboard-plugin-wit==1.8.1
        - test-tube==0.7.5
        - threadpoolctl==3.1.0
        - tifffile==2022.10.10
        - timm==0.6.11
        - tokenizers==0.12.1
        - torch==1.13.0+cu116
        - torch-fidelity==0.3.0
        - torchaudio==0.13.0+cu116
        - torchdiffeq==0.2.3
        - torchmetrics==0.6.0
        - tqdm==4.64.1
        - transformers==4.19.2
        - typing-inspect==0.8.0
        - urwid==2.1.2
        - wandb==0.13.5
        - wcwidth==0.2.5
        - werkzeug==2.2.2
        - yarl==1.8.1
        - zipp==3.10.0
        - -e git+https://github.com/openai/CLIP.git@main#egg=clip
        - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
        - -e git+https://github.com/lstein/k-diffusion.git@master#egg=k-diffusion
        - -e git+https://github.com/lstein/GFPGAN@fix-dark-cast-images#egg=gfpgan
        - -e git+https://github.com/xinntao/Real-ESRGAN#egg=realesrgan
        - -e .
